---
log_interval: 100
log_dir: log

model:
  input_feat_dims: 5
  hidden_dims: 32
  num_layers: 4
  num_relations: 3
  trans_pooling: True
  
dataset:
  edge_dropout: 0.
  batch_size: 512
  ui: True
  us: True
  si: True

train:
  device: 0
  epochs: 20
  learning_rates:
    - 0.001
    - 0.002
    - 0.0005
  weight_decay: 0.0
  lr_decay_step: 5
  lr_decay_factor: 0.98

